version: "2.1"

services:
  app:
    build: .
    command: node_modules/.bin/nodemon src/index.js
    ports: 
      - "3030:3030"
    environment:
      - PORT=3030
      - NODE_ENV=development
      - SECRET=d9d08ed0ffe7e988f11f9b76cf792626
    depends_on: 
      db:
        condition: service_healthy
    links:
      - db
    volumes:
      - .:/app
      
  db:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ebom
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
